export const SUBS = [
  { id: 'gp', name: 'Game Pass Ultimate', price: 29.99, short: 'GP' },
  { id: 'pse', name: 'PS Plus Essential', price: 9.99, short: 'PSE' },
  { id: 'psx', name: 'PS Plus Extra', price: 17.99, short: 'PSX' },
  { id: 'psp', name: 'PS Plus Premium', price: 22.99, short: 'PSP' },
  { id: 'ea', name: 'EA Play', price: 4.99, short: 'EA' },
  { id: 'ubi', name: 'Ubisoft+', price: 17.99, short: 'UBI' },
  { id: 'nso', name: 'Nintendo Switch Online', price: 3.99, short: 'NSO' },
  { id: 'hc', name: 'Humble Choice', price: 11.99, short: 'HC' },
];

export const GAMES = [
  { id: 1, name: "Starfield", subs: ['gp'] },
  { id: 2, name: "Forza Horizon 5", subs: ['gp'] },
  { id: 3, name: "Hades II", subs: ['gp', 'psx', 'psp'] },
  { id: 4, name: "Hi-Fi Rush", subs: ['gp'] },
  { id: 5, name: "Marvel's Spider-Man 2", subs: ['psx', 'psp'] },
  { id: 6, name: "God of War Ragnarök", subs: ['psx', 'psp'] },
  { id: 7, name: "Horizon Forbidden West", subs: ['psx', 'psp'] },
  { id: 8, name: "The Last of Us Part I", subs: ['psx', 'psp'] },
  { id: 9, name: "Minecraft", subs: ['gp'] },
  { id: 10, name: "Sea of Thieves", subs: ['gp'] },
  { id: 11, name: "Hollow Knight: Silksong", subs: [] },
  { id: 12, name: "Death Stranding 2", subs: ['psx', 'psp'] },
  { id: 13, name: "Assassin's Creed Mirage", subs: ['ubi'] },
  { id: 14, name: "Far Cry 6", subs: ['ubi'] },
  { id: 15, name: "It Takes Two", subs: ['ea', 'gp'] },
  { id: 16, name: "Battlefield 2042", subs: ['ea', 'gp'] },
  { id: 17, name: "Zelda: Tears of the Kingdom", subs: ['nso'] },
  { id: 18, name: "Mario Kart 8 Deluxe", subs: ['nso'] },
  { id: 19, name: "Lies of P", subs: ['gp', 'psx', 'psp'] },
  { id: 20, name: "Palworld", subs: ['gp'] },
  { id: 21, name: "Doom: The Dark Ages", subs: ['gp'] },
  { id: 22, name: "Clair Obscur: Expedition 33", subs: [] },
  { id: 23, name: "Kingdom Come: Deliverance II", subs: ['gp'] },
  { id: 24, name: "Helldivers 2", subs: ['psx', 'psp'] },
  { id: 25, name: "Elden Ring", subs: ['psx', 'psp'] },
  { id: 26, name: "Cyberpunk 2077", subs: ['gp', 'psx', 'psp'] },
  { id: 27, name: "Red Dead Redemption 2", subs: ['psx', 'psp'] },
  { id: 28, name: "A Plague Tale: Requiem", subs: ['gp', 'psx', 'psp'] },
  { id: 29, name: "Ori and the Will of the Wisps", subs: ['gp'] },
  { id: 30, name: "Control", subs: ['gp', 'psx', 'psp', 'hc'] },
];
